### PR TITLE
What did I get myself into...

### PR DESCRIPTION
**Pull request by taubenangriff**
dependency injection is easy they said... it will be much fun they said..

### CODE REVIEW

**Comment by jakobharder** [comment]
You‘re sure you‘re not over complicating things?

**Comment by taubenangriff** [comment]
no

**Comment by taubenangriff** [comment]
This branch builds again at least. (Don't talk about the tests)

### What underwent major changes 
- Mod loading / Mod Collection loading is done via factory 
- ModTweaker IO is different (file format stays same ofc).
- Hooks are a little different and have to be registered in a modcollection.
- githubrepoinfo strategies simplified: instead of a strategy pattern in the githubrepoinfo we use it where it is needed, and inject it with DI. 

### Problems
- IValueConverters. Screw them.

I can't believe I did this just because I hated the GithubClientProvider with the static client so much.

**Comment by taubenangriff** [comment]
Converters work now. After configuring the services, They are added to the resource dictionaries in code behind. I know, it's hacky, but it works. @jakobharder you decide, if it's worth fixing the tests, I'll do it. If it's not worth, this branch can be scrapped.

**Comment by taubenangriff** [comment]
Okay, branch works and the subfolder thing is also in there. Make or break, this gonna get merged or nuked?

**Pull request merged**
