### PR TITLE
detect when mod was externally deleted

### PR DESCRIPTION
**Pull request by jakobharder**
Actions like deactivate will trigger a check and mark mods as removed when their folder doesn't exist anymore.

Properly updated on reinstall or delete actions. Delete won't ask for confirmation in this case.

image

### CODE REVIEW

**Comment by jakobharder** [comment]
Ah, I forgot to change the temp folder name for one of the tests. Parallel execution doesn't like that ^^

**Comment by jakobharder** [comment]
Setting this to draft.
There still seems to be a very odd issue with the unit tests...

**Comment by jakobharder** [comment]
The other tests were deleting the complete `tmp` folder as part of their test. I chose to use `temp` not touch them unnecessarily.

**Comment by taubenangriff** [comment]
💯

**Review by taubenangriff — APPROVED** [review]

**Pull request merged**
