### PR TITLE
add json based modindex

### LINKED ISSUE #114: Github Browsing needs to get Data from Github
We need an IRepoInfoSource that gets its data from a github repository instead of a static definition.

### PR DESCRIPTION
**Pull request by jakobharder**
There's a setting that defaults to `resource/modindex.json` containing what `StaticRepoInfoSource` had before.

Try `https://raw.githubusercontent.com/jakobharder/Collection/devel/modindex/modindex.json` in the settings to check URL based modindex.

The current implementation doesn't depend on GitHub which is preferable IMO.

We could start using this in `anno-mods/collection` or flesh out the mod repo stored `package.json` before doing so.

Closes #114 ?

### CODE REVIEW

**Comment by taubenangriff** [comment]
looks good as the first implementation. 

I am not tooo sure we should skip the mod repo definition, since that means corrections of the download asset need to be made on the source repo, not the mod repo itself. I have fucked those things up too often in the past...

**Comment by taubenangriff** [comment]
oh, and instead of writing json, I think we should set up a repo similar to anno-mods/GuidRanges since that worked fairly well so far.
Then autogenerate the json based on the table on every commit that changes the table :)

**Review by taubenangriff — APPROVED** [review]

**Comment by jakobharder** [comment]
Agreed, mod repo json with the download is something we should do.
I just want to have a working version now (and maybe optional fallbacks later if needed). 😆

> autogenerate the json based on the table

💯 well then, setup the table ;-)

**Comment by taubenangriff** [comment]
as good as done boss

**Pull request merged**
