### PR TITLE
Expand and clean installation view

### PR DESCRIPTION
**Pull request by taubenangriff**
image

- proposed UI implementation for installs directly from Github
- marks the hints as such
- Seperate modloader, gamepath, zip install and github installs
- Show number of active installs

This is currently UI only, many things are rough. If the UI side is good, this can proceed to implementation

### CODE REVIEW

**Comment by taubenangriff** [comment]
> Buttons with following dialog should have "...".

I disagree. With file selection, one is used to either "..." or "browse", but with github? I see that "Select" might be a little vague, but "..." is not better. 

> "Configure for auto updating": Is this intended to be per mod? If so, we need a place to change it afterwards.

This is intended to do per mod. The place to change it afterwards should be in the mod activation view, something we can do later on. ^^

> "Enabled" in Modloader section is difficult to understand what it is for. How about "temporarily disable modloader"?

I am open for discussion on that

> "Active installs: 0". Is that info helpful here? I can see it in the mod list, but here not so much imho.

The right side is intended to be an overview of what you install right now. If you add many installs at once, the view also becomes scollable, in which case it might be helpful to see the number of active installs.

**Comment by jakobharder** [comment]
> I disagree. With file selection, one is used to either "..." or "browse", but with github? I see that "Select" might be a little vague, but "..." is not better.

I mean "Select..." etc. ;-)

**Comment by taubenangriff** [comment]
> An alternative/addition I see is to have a button "Start without Mods" directly under "Start Anno 1800".

or conveniently add a toggle underneath the start button?

> My concern is the installation page becomes overwhelming with information and it is difficult to visually guide a user to the important pieces.

Maybe this would be helped by not having that big amounts of options visible all the time. 

1) having to expand the options to change them. 

2) having to set them only after you click on the select button.

**Comment by taubenangriff** [comment]
image

Current state of the UI

**Pull request merged**
