### PR TITLE
Experimental: Markdown

### PR DESCRIPTION
**Pull request by taubenangriff**
I played around with this lib a little bit which displays markdown using flow documents: https://github.com/theunrepentantgeek/Markdown.XAML

Idk if it's good, it's certainly lightweight. These are the first results - attached a little test mod.

image

[[Gameplay] MarkdownTest.zip](https://github.com/anno-mods/iModYourAnno/files/8578632/Gameplay.MarkdownTest.zip)

### CODE REVIEW

**Comment by taubenangriff** [comment]
#35

**Comment by jakobharder** [comment]
Works well with my existing markdowns 👍

For sure there's some style polish to do, but that isn't needed for the first PR.

**Review by jakobharder — APPROVED** [review]

**Comment by taubenangriff** [comment]
Question @jakobharder do you think we should make markdown an option that has to specifically be enabled in the modinfo?

**Comment by jakobharder** [comment]
> Question @jakobharder do you think we should make markdown an option that has to specifically be enabled in the modinfo?

Newline behavior is a little different, so it would make sense to distinguish between text and markdown.

I'm not a fan of the inline description in the json files, as I always have a .md file in the mod as well for easier reading.

=> Instead of a markdown option, how about a use-this-file-option alternative and decide based on .txt vs .md which it is? Inline descriptions don't get markdown support then.

**Comment by taubenangriff** [comment]
How about a file embed in the actual description: 

if we have a description that could match via regex to something like `"{file::description_english.md}"` and the file is found we drop the description and embed a file via markdown instead.

**Comment by jakobharder** [comment]
Personally, I'd simply match against single line matching against a text or markdown file, .i.e `"English": "foo/bar.md"`. If the file doesn't exist, the path is shown.

Something like `"English": "{file:foo/bar.md}"` would only make sense if it's embedded into the text as a way to include text snippets, meaning the following is allowed `"English": "Text\n{file:footer.md}"`.

**Comment by taubenangriff** [comment]
[[Gameplay] MarkdownTest (2).zip](https://github.com/anno-mods/iModYourAnno/files/8837664/Gameplay.MarkdownTest.2.zip)

test mod

**Review by jakobharder — APPROVED** [review]

**Pull request merged**
